### ISSUE TITLE
Java error during editing

### ISSUE THREAD

**Issue by paulwrightwork** [kornilova203/matlab-IntelliJ-plugin#109]
Editing a .m file in PyCharm, the following IDE error was reported:

```text
java.lang.Throwable: atlases
 parent=for atlases

%% Mask the base image to try to remove the headrest
Nb = nifti('/workdir/inputs/baseimage.nii');
Nm = nifti('/workdir/native_atlases/wCTseg_tpm_atlas.nii');
Nbb = Nb;
Nbb.dat.fname = '/workdir/inputs/bbaseimage.nii';
Nbb.dat(:) = Nb.dat(:) .* (Nm.dat(:)>0);
create(Nbb);

%% Compute thresholded mean lesion
masks = spm_select('fplist', '/workdir/inputs/masks', '.*\.nii$');
if isempty(masks)
    error('No lesion masks found. Check lesion segmentation was successful and that images were gunzipped.')
end

Vm = spm_vol(masks);
Ym = spm_read_vols(Vm);
Yl = mean(Ym,4) > 0.5;
% Zero lesion outside the cranium.m
Yl((Nm.dat(:) == 0) | (Nm.dat(:) > 3)) = 0;

%% Combine TPMs by indexing maximum voxel
tpms = char('/workdir/inputs/c1baseimage.nii', ...
            '/workdir/inputs/c2baseimage.nii', ...
            '/workdir/inputs/c3baseimage.nii');
Vt = spm_vol(tpms);
% Read in TPMs as 4D matrix
Yt = spm_read_vols(Vt);
% Threshold at 0.5
Yt(Yt<=0.5) = 0;
% Find maximum probability
tmax = max(Yt,[],4);
% Expand to 4D
tmaxes = repmat(tmax,[1 1 1 3]);
% Find voxels that equal the max
twinner = (Yt == tmaxes);
% Assign the voxel to whichever volume contained the max
Ytc = twinner(:,:,:,1) + 2*twinner(:,:,:,2) + 3*twinner(:,:,:,3);
% Only keep voxels where there there was a single volume containing the max
Ytc = Ytc .* (sum(twinner,4)==1);

%% Add lesion to tissue image and save
Ytc(Yl) = 4;
Vtc = spm_vol;
Vtc(1).fname = '/workdir/tissues.nii';
Vtc.dim = size(Ytc);
Vtc.dt = [spm_type('uint8') 0];
Vtc.pinfo = [1 0 352]';
Vtc.mat = Vt(1).mat;
spm_write_vol(Vtc,Ytc);

%% Affine base image and combined masks to MNI space
paths = {{'/workdir/inputs/bbaseimage.nii'} {'/workdir/tissues.nii'}};
opt = struct( ...
    'dir_out', '/workdir/mniaffine', ...
    'prefix', 'p', ...
    'do', struct( ...
        'real_mni', true, ...
        'vx',       true, ...
        'bb_spm',   true), ...
    'realign2mni', struct('rigid', false), ...
    'vx', struct('size', 1) ...
    );
out = RunPreproc(paths,opt);

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:284)
	at com.intellij.psi.impl.PsiElementBase.findNotNullChildByClass(PsiElementBase.java:307)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopRangeImpl.getAssignExpr(MatlabForLoopRangeImpl.java:32)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitForLoop(MatlabControlFlowBuilder.kt:52)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:25)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:751)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.visitFor(ControlFlowBuilder.java:266)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.build(ControlFlowBuilder.java:259)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.buildControlFlow(MatlabControlFlowBuilder.kt:16)
	at com.github.kornilova203.matlab.inspections.MatlabUnreachableCodeInspection$buildVisitor$1.visitFile(MatlabUnreachableCodeInspection.kt:18)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:352)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:352)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by crisluengo** [comment]
I had exactly the same error and same stack trace.

The error for me read:
```none
java.lang.Throwable: older
 parent=for older MATLABs. It is the default option since R2010b or R2011a (release notes are ambiguous)

mex(varargin{:},dipopts{:});
```
followed by the exact same stack trace as above.

It happened while converting this line:
```matlab
% TODO: add -largeArrayDims for older MATLABs. It is the default option since R2010b or R2011a (release notes are ambiguous)
```
into this line:
```matlab
dipopts{end+1} = '-largeArrayDims'; % This is necessary for older MATLABs. It is the default option since R2010b or R2011a (release notes are ambiguous)
```
I think I typed `dipopts{end+1} = '` above the comment, then deleted the beginning part of the comment ("`% TODO: add `") as well as the newline, and then added a quote after `-largeArrayDims`.
