### ISSUE TITLE
Completion error 

### ISSUE THREAD

**Issue by kripnerl** [kornilova203/matlab-IntelliJ-plugin#116]
Hello, 

just leaving here for your convenience. Error is not braking anything. No idea how to reproduce. 

```
java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiElement.getPrevSibling()" because the return value of "com.intellij.psi.PsiElement.getPrevSibling()" is null
	at com.github.kornilova203.matlab.completion.MatlabLibraryFunctionCompletionContributor$1.addCompletions(MatlabLibraryFunctionCompletionContributor.kt:44)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:23)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$getVariantsFromContributor$0(CompletionServiceImpl.java:333)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpan(trace.kt:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.getVariantsFromContributor(CompletionServiceImpl.java:332)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:73)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:150)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:87)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:23)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$getVariantsFromContributor$0(CompletionServiceImpl.java:333)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpan(trace.kt:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.getVariantsFromContributor(CompletionServiceImpl.java:332)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:73)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:56)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:130)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:48)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$performCompletion$1(CompletionServiceImpl.java:351)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpan(trace.kt:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:340)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$11(CompletionProgressIndicator.java:871)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:213)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:721)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:212)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:867)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:855)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:373)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:160)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$8(CodeCompletionHandlerBase.java:364)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

Setup info: 

`PY-232.9559.58, JRE 17.0.8+7-b1000.8x64 JetBrains s.r.o., OS Linux(amd64) v6.2.0-31-generic, screens 1920.0x1080.0, 1920.0x1200.0, 1920.0x1200.0`

**Comment by kripnerl** [comment]
Some more errors:  :-)

```
java.lang.Throwable: j
 parent=for j 
% vessel
G.rv = tok.pf_passive.loop(0).element(:).geometry.rectangle.r;
G.zv = tok.pf_passive.loop(0).element(:).geometry.rectangle.z;
G.wv = tok.pf_passive.loop(0).element(:).geometry.rectangle.width;
G.hv = tok.pf_passive.loop(0).element(:).geometry.rectangle.height;
G.Rv = tok.pf_passive.loop(0).element(:).geometry.rectangle.resistance;

% @TODO this is a very rough incorporation of passive plates (as an "extension" of the vessel)
if true
    loop1 = tok.pf_passive.loop(1).element(1).geometry.outline;
    loop2 = tok.pf_passive.loop(2).element(1).geometry.outline;
    n_psp = P.n_psp;
    
    % @TODO HARDCODED order of elements
    G.rv = [G.rv; linspace(loop1.r(4), loop1.r(3), n_psp)'; linspace(loop2.r(4), loop2.r(3), n_psp)'];
    G.zv = [G.zv; linspace(loop1.z(4), loop1.z(3), n_psp)'; linspace(loop2.z(4), loop2.z(3), n_psp)'];
    G.wv = [G.wv; 0.02*ones(2*n_psp, 1)];  % @TODO hardcoded size of filament
    G.hv = [G.hv; 0.02*ones(2*n_psp, 1)];  % @TODO hardcoded size of filament
    G.Rv = [G.Rv; 1e-2*G.Rv(1:2*n_psp)];  % @TODO reusing resistance values from vessel
    
    % passive plates - specify Tvu, dimu here to avoid automatic generation of
    % thereof later in the code (file meqg.m, lines 103-162).
    Tvu_vessel = eye(length(G.rv)-2*n_psp);
    Tvu_psp = null([ones(1, n_psp) +ones(1, n_psp)]);
    G.Tvu = blkdiag(Tvu_vessel, Tvu_psp);
    G.dimu = cellstr(num2str((1:size(G.Tvu, 2))','v%03d'));
    G.Ru = diag(G.Tvu'*diag(G.Rv)*G.Tvu);
    G.nv = numel(G.rv);
    G.nu = size(G.Tvu, 2);
end


% limiter
G.rl = tok.wall.description_2d.limiter.unit.outline.r;
G.zl = tok.wall.description_2d.limiter.unit.outline.z;


% windings
nc = length(tok.pf_active.coil);
nw = 0;
for i = 1:nc
    nw = nw + length(tok.pf_active.coil(i).element);
end

G.rw = zeros(nw, 1);
G.zw = zeros(nw, 1);
G.ww = zeros(nw, 1);
G.hw = zeros(nw, 1);
G.Rw = zeros(nw, 1);
G.Tcw = zeros(nc, nw);

% What is going on here?
%   - i_wind iterates over each winding globally (1:nw)
%   - i_coil iterates over each coil (1:nc), j iterates ONLY this coil's windings
i_wind = 0;
for i_coil = 1:nc
    turns = length(tok.pf_active.coil(i_coil).element);
    for j = 1:turns
        i_wind = i_wind + 1;
        G.Tcw(i_coil, i_wind) = 1;
        G.rw(i_wind) = tok.pf_active.coil(i_coil).element(j).geometry.rectangle.r;
        G.zw(i_wind) = tok.pf_active.coil(i_coil).element(j).geometry.rectangle.z;
        G.ww(i_wind) = tok.pf_active.coil(i_coil).element(j).geometry.rectangle.width;
        G.hw(i_wind) = tok.pf_active.coil(i_coil).element(j).geometry.rectangle.height;
        G.Rw(i_wind) = tok.pf_active.coil(i_coil).resistance / turns;
        
        % TODO Temporary fix of incorrect resistance values.
        G.Rw(i_wind) = G.Rw(i_wind) * 1e-6;
    end
end

G.dw = nan(size(G.rw));  % no diameter, rectangular windings

% coils
nc = length(tok.pf_active.coil);
na = length(tok.pf_active.supply);
G.rc = zeros(nc, 1);
G.zc = zeros(nc, 1);
G.wc = zeros(nc, 1);
G.hc = zeros(nc, 1);

for i = 1:nc
    rmin = tok.pf_active.coil(i).element(1).geometry.rectangle.r;
    rmax = tok.pf_active.coil(i).element(1).geometry.rectangle.r;
    zmin = tok.pf_active.coil(i).element(1).geometry.rectangle.z;
    zmax = tok.pf_active.coil(i).element(1).geometry.rectangle.z;
    for j_el = 1:length(tok.pf_active.coil(i).element)
        rmin = min(rmin, tok.pf_active.coil(i).element(j_el).geometry.rectangle.r);
        rmax = max(rmax, tok.pf_active.coil(i).element(j_el).geometry.rectangle.r);
        zmin = min(zmin, tok.pf_active.coil(i).element(j_el).geometry.rectangle.z);
        zmax = max(zmax, tok.pf_active.coil(i).element(j_el).geometry.rectangle.z);
    end
    G.rc(i) = (rmin + rmax) / 2;
    G.zc(i) = (zmin + zmax) / 2;
    G.wc(i) = (rmax - rmin);
    G.hc(i) = (zmax - zmin);
end

G.Tca = zeros(nc, na);

for i = 1:length(tok.pf_active.circuit)
    % TODO Matrix connections is transposed vs. the IMAS specification
    %      See issue in nice-workspace about h5load.m
    connections = tok.pf_active.circuit(i).connections';
    conn_dims = size(connections);
    
    idx_coils = zeros(nc, 1);
    idx_supply = zeros(na, 1);
    for j = 1:conn_dims(1)
        idx_coils = idx_coils | connections(j,2*na+1:2:2*na+2*nc)';
        idx_supply = idx_supply | connections(j,1:2:2*na)';
    end

    G.Tca(idx_coils, idx_supply) = 1;
end

% interconnection matrix windings-active circuits (the IMPORTANT one)
G.Twa = G.Tcw' * G.Tca;

% flux loops
posf = [tok.magnetics.flux_loop.position];
G.rf = [posf.r]';
G.zf = [posf.z]';

posm = [tok.magnetics.b_field_pol_probe.position];
G.rm = [posm.r]';
G.zm = [posm.z]'; 
% IDS define the poloidal angle as clockwise, here it is transformed 
% to anticlockwise notation
G.am = mod(-[tok.magnetics.b_field_pol_probe.poloidal_angle]', 2*pi);

% Wall gaps (lk clearences)
% G.rW  = P.r0 +          P.al*cos(thW);
% G.zW  =    0 + 1*P.al*sin(thW);
% G.oW  = -thW;
% G.aW  = repmat(2*P.av,size(thW));

% dimension labels
G.dima = cellstr(num2str((1:size(G.Twa,2))','PF_%03d'));

G.dimc = cellstr(num2str((1:size(G.Tca,1))','Coil_%03d'));
G.dimf = cellstr(num2str((1:numel(G.rf))','Ff_%03d'));
G.dimm = cellstr(num2str((1:numel(G.rm))','Bm_%03d'));
G.dimv = cellstr(num2str((1:numel(G.rv))','vv_%03d'));
% G.dimW = cellstr(num2str((1:numel(G.rW))','gap_%03d'));

% vessel specification needed in liu
if isfield(P,'selu')
  switch P.selu
    case 's'
      if ~isfield(P,'nu'), P.nu = P.nv; end
      G.Tvs = eye(P.nu); G.dims=cellstr(num2str((1:numel(P.nu))','vs_%03d'));
  end
end

% Power supplies
G.Valim   = inf(numel(G.dima),1);
G.Ialim   = inf(numel(G.dima),1);
G.Talim   = inf(numel(G.dima),1);
end
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:280)
	at com.intellij.psi.impl.PsiElementBase.findNotNullChildByClass(PsiElementBase.java:301)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopRangeImpl.getAssignExpr(MatlabForLoopRangeImpl.java:32)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitForLoop(MatlabControlFlowBuilder.kt:52)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:25)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitElement(MatlabControlFlowBuilder.kt:20)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitPsiElement(MatlabVisitor.java:407)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitBlock(MatlabVisitor.java:39)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:25)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitFunctionDeclaration(MatlabControlFlowBuilder.kt:175)
	at com.github.kornilova203.matlab.psi.impl.MatlabFunctionDeclarationImpl.accept(MatlabFunctionDeclarationImpl.java:32)
	at com.github.kornilova203.matlab.psi.impl.MatlabFunctionDeclarationImpl.accept(MatlabFunctionDeclarationImpl.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:183)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:747)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.visitFor(ControlFlowBuilder.java:276)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.build(ControlFlowBuilder.java:269)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.buildControlFlow(MatlabControlFlowBuilder.kt:16)
	at com.github.kornilova203.matlab.inspections.MatlabUnreachableCodeInspection$buildVisitor$1.visitFile(MatlabUnreachableCodeInspection.kt:18)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:59)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:334)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:342)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:348)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:311)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:311)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:314)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:299)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:367)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:310)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:285)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:138)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:227)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:95)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
