### ISSUE TITLE
Exception in plugin Matlab Support (0.8.1)

### ISSUE THREAD

**Issue by crisluengo** [kornilova203/matlab-IntelliJ-plugin#96]
To me this looks similar to #95, which was fixed in 0.8.1, the version of the plugin that I'm using.

I'm using CLion 2020.2.4 (Oct 7), on macOS.

```
java.lang.ClassCastException: class com.github.kornilova203.matlab.psi.impl.MatlabCellArrayAccessExprImpl cannot be cast to class com.github.kornilova203.matlab.psi.MatlabRefExpr (com.github.kornilova203.matlab.psi.impl.MatlabCellArrayAccessExprImpl and com.github.kornilova203.matlab.psi.MatlabRefExpr are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @12d5af6b)
	at com.github.kornilova203.matlab.MatlabEvaluatorKt.evaluateExpr(MatlabEvaluator.kt:23)
	at com.github.kornilova203.matlab.MatlabEvaluatorKt.evaluateBinaryExpr(MatlabEvaluator.kt:39)
	at com.github.kornilova203.matlab.MatlabEvaluatorKt.evaluateExpr(MatlabEvaluator.kt:20)
	at com.github.kornilova203.matlab.MatlabEvaluatorKt.evaluateBinaryExpr(MatlabEvaluator.kt:40)
	at com.github.kornilova203.matlab.MatlabEvaluatorKt.evaluateExpr(MatlabEvaluator.kt:20)
	at com.github.kornilova203.matlab.MatlabEvaluatorKt.evaluateAsBoolean(MatlabEvaluator.kt:9)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitIfBlock(MatlabControlFlowBuilder.kt:71)
	at com.github.kornilova203.matlab.psi.impl.MatlabIfBlockImpl.accept(MatlabIfBlockImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabIfBlockImpl.accept(MatlabIfBlockImpl.java:25)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitElement(MatlabControlFlowBuilder.kt:20)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitPsiElement(MatlabVisitor.java:407)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitBlock(MatlabVisitor.java:39)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:25)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitForLoop(MatlabControlFlowBuilder.kt:56)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:25)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitElement(MatlabControlFlowBuilder.kt:20)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitPsiElement(MatlabVisitor.java:407)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitBlock(MatlabVisitor.java:39)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:25)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitForLoop(MatlabControlFlowBuilder.kt:56)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabForLoopImpl.accept(MatlabForLoopImpl.java:25)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitElement(MatlabControlFlowBuilder.kt:20)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitPsiElement(MatlabVisitor.java:407)
	at com.github.kornilova203.matlab.psi.MatlabVisitor.visitBlock(MatlabVisitor.java:39)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:21)
	at com.github.kornilova203.matlab.psi.impl.MatlabBlockImpl.accept(MatlabBlockImpl.java:25)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.visitFunctionDeclaration(MatlabControlFlowBuilder.kt:175)
	at com.github.kornilova203.matlab.psi.impl.MatlabFunctionDeclarationImpl.accept(MatlabFunctionDeclarationImpl.java:32)
	at com.github.kornilova203.matlab.psi.impl.MatlabFunctionDeclarationImpl.accept(MatlabFunctionDeclarationImpl.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:753)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.visitFor(ControlFlowBuilder.java:266)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.build(ControlFlowBuilder.java:259)
	at com.github.kornilova203.matlab.MatlabControlFlowBuilder.buildControlFlow(MatlabControlFlowBuilder.kt:16)
	at com.github.kornilova203.matlab.inspections.MatlabUnreachableCodeInspection$buildVisitor$1.visitFile(MatlabUnreachableCodeInspection.kt:18)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$6(LocalInspectionsPass.java:319)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:319)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1105)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1708)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:67)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitRestElementsAndCleanup(LocalInspectionsPass.java:330)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:195)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by kornilova203** [comment]
Hello @crisluengo,
Sorry for slow reply
I removed all casts that may produce ClassCastException and I'll upload new plugin version now

Closed by 8831234d1dd15bd8972fe77a8757c140d5f495e5
